/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import akka.actor.typed.ActorSystem;

import com.telmomenezes.jfastemd.*;

import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.concurrent.TimeUnit;
import java.util.Scanner;
import java.util.List;
import java.util.LinkedList;
import java.util.ArrayList;
import java.io.BufferedWriter;
import java.io.FileWriter;

public class VideoZillaMain {

    static Signature getNDSignature(String fileName) throws FileNotFoundException {
        Scanner scanner = new Scanner(new File(fileName)); 
        List<Double> list = new LinkedList<>();
        while (scanner.hasNextDouble()) {
            list.add(scanner.nextDouble());
        }
        scanner.close();

        int n = list.size() / 1024;
        System.out.println(n);
        FeatureND[] features = new FeatureND[n];
        double[] weights = new double[n];

        for (int i = 0; i < n; i++) {
            List<Double> tmp = new ArrayList<>();
            tmp.add(list.get(i));
            tmp.add(list.get(i + n));
            FeatureND f = new FeatureND(tmp);
            features[i] = f;
            weights[i] = 1.0 / n;
        }
        
        Signature signature = new Signature();
        signature.setNumberOfFeatures(n);
        signature.setFeatures(features);
        signature.setWeights(weights);
        signature.setLabel("test");

        return signature;
    } 

    public static void main(String[] args) {
        // Created ActorSystem and top level supervisor
        final ActorSystem<IndexSupervisor.Command> indexSupervisor = ActorSystem.create(IndexSupervisor.create(), "zilla-system");

        // Build index
        indexSupervisor.tell(new IndexSupervisor.UserTrackCamera("1", "1"));
        indexSupervisor.tell(new IndexSupervisor.UserTrackCamera("1", "2"));
        indexSupervisor.tell(new IndexSupervisor.UserTrackCamera("1", "3"));
        indexSupervisor.tell(new IndexSupervisor.UserTrackCamera("1", "4"));
        
        // give some time for threads to spawn
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (Exception e) {
        }

        // Actual query here
        // Cluster query example
        try {
            Signature targetSignature = getNDSignature("./data/feature1-10.csv");
            indexSupervisor.tell(new IndexSupervisor.UserRequestSignaturesBySignature(1, "1", targetSignature));
            // Direct query example 
            Feature[] features = targetSignature.getFeatures();
            indexSupervisor.tell(new IndexSupervisor.UserRequestSignaturesByFeature(1, "1", (FeatureND) features[0]));
        } catch (Exception e) {
        }

        // Terminate Video-zilla
        indexSupervisor.terminate();
    }
}
